
[redhat-vscode-yaml]
src.openvsx = "redhat.vscode-yaml"
fetch.openvsx = "redhat.vscode-yaml"

[redhat-vscode-yaml.passthru]
name = "vscode-yaml"
publisher = "redhat"
marketplaceName = "vscode-yaml"
marketplacePublisher = "redhat"
license = "mit"
description = "YAML Language Support by Red Hat, with built-in Kubernetes syntax support"
changelog = "https://open-vsx.org/api/redhat/vscode-yaml/1.9.1/file/CHANGELOG.md"
downloadPage = "https://open-vsx.org/api/redhat/vscode-yaml/1.9.1/file/redhat.vscode-yaml-1.9.1.vsix"
homepage = "https://github.com/redhat-developer/vscode-yaml#readme"
