name: Update Extensions

on:
  # Enable manual trigger
  workflow_dispatch:
  # Trigger every day
  schedule:
    - cron: "0 0 * * *"
  push:

env:
  nixpkgs: nixpkgs=https://github.com/NixOS/nixpkgs/archive/cd87aef066e4bdbb1139845500072bd252d37c5e.tar.gz
  extra_nix_config: |
    substituters = https://cache.nixos.org https://nix-community.cachix.org https://fog.cachix.org
    trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY= nix-community.cachix.org-1:mB9FSh9qf2dCimDSUo8Zy7bkq5CX+/rkCWyvRCYg3Fs= fog.cachix.org-1:FAxiA6qMLoXEUdEq+HaT24g1MjnxdfygrbrLDBp6U/s=

  run_updater: export DENO_DIR=.deno && nix run nixpkgs#deno -- run --allow-write --allow-net={0} --no-prompt updater/index.ts {1} nvfetch/{2}.toml

  vscode: vscode-marketplace

  nvfetch_workflow: ./.github/workflows/nvfetch.yaml
  commit_and_push: |
    git config user.name github-actions
    git config user.email github-actions@github.com
    git add nvfetch/{0}.toml
    git diff --quiet && git diff --staged --quiet || git commit -m "action: update {1} extensions"
    git push

# https://docs.github.com/en/actions/learn-github-actions/expressions#example-returning-a-json-object
# https://docs.github.com/en/actions/using-jobs/defining-outputs-for-jobs#example-defining-outputs-for-a-job

jobs:
  read-config:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Save config
        id: set-matrix
        run: echo "matrix=$(jq -c . < .github/workflows/config.json)" >> $GITHUB_OUTPUT

  update-extensions:
    needs: read-config
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{ fromJSON(needs.read-config.outputs.matrix) }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install latest Nix
        uses: cachix/install-nix-action@v18
        with:
          extra_nix_config: ${{ env.extra_nix_config }}
          nix_path: ${{ env.nixpkgs }}

      - name: Run Updater on ${{ matrix.name }} extensions
        run: ${{ format(env.run_updater, matrix.allow_net, matrix.target, matrix.target) }}

      - name: Commit and push changes
        run: ${{ format(env.commit_and_push, matrix.target, matrix.target) }}

  # Assume no race conditions when pushing

  nvfetch-vscode-marketplace-1:
    needs: update-extensions
    uses: ./.github/workflows/nvfetch.yaml
    with:
      NAME: vscode-marketplace
      FIRST_BLOCK: 1
      BLOCK_LIMIT: 1
      ACTION_ID: 1
      # FIRST_BLOCK: 1
      # BLOCK_LIMIT: 100

  nvfetch-vscode-marketplace-2:
    needs: update-extensions
    uses: ./.github/workflows/nvfetch.yaml
    with:
      NAME: vscode-marketplace
      FIRST_BLOCK: 2
      BLOCK_LIMIT: 1
      ACTION_ID: 2
      # FIRST_BLOCK: 101
      # BLOCK_LIMIT: 100

  nvfetch-vscode-marketplace-3:
    needs: update-extensions
    uses: ./.github/workflows/nvfetch.yaml
    with:
      NAME: vscode-marketplace
      FIRST_BLOCK: 3
      BLOCK_LIMIT: 1
      ACTION_ID: 3
      # FIRST_BLOCK: 201
      # BLOCK_LIMIT: 100

  # nvfetch-vscode-marketplace-4:
  #   needs: update-extensions
  #   uses: ./.github/workflows/nvfetch.yaml
  #   with:
  #     NAME: vscode-marketplace
  #     FIRST_BLOCK: 301
  #     BLOCK_LIMIT: 100

  # nvfetch-vscode-marketplace-5:
  #   needs: update-extensions
  #   uses: ./.github/workflows/nvfetch.yaml
  #   with:
  #     NAME: vscode-marketplace
  #     FIRST_BLOCK: 401
  #     BLOCK_LIMIT: 100

  # nvfetch-vscode-marketplace-6:
  #   needs: update-extensions
  #   uses: ./.github/workflows/nvfetch.yaml
  #   with:
  #     NAME: vscode-marketplace
  #     FIRST_BLOCK: 501
  #     BLOCK_LIMIT: 100

  combine-vscode-marketplace:
    needs:
      [
        nvfetch-vscode-marketplace-1,
        nvfetch-vscode-marketplace-2,
        nvfetch-vscode-marketplace-3,
      ]
    uses: ./.github/workflows/combine.yaml
    with:
      NAME: vscode-marketplace
      NUMBER_ACTIONS: 4
